CREATE DATABASE VDD;
USE VDD;
CREATE TABLE user (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(64),
  email VARCHAR(254),
  password VARCHAR(254),
  createAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);